//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Used_Book_Selling_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class tbl__book
    {
        
        public int seller_id { get; set; }
        [DisplayName("Book Title")]
        public string title { get; set; }
        [DisplayName("Book Edition")]
        public int edition { get; set; }
        [DisplayName("Author Name")]
        public string author { get; set; }
        [DisplayName("Publisher")]
        public string publisher { get; set; }
        [DisplayName("Language")]
        public string language { get; set; }
        [DisplayName("Book Type")]
        public string book_type { get; set; }
        [DisplayName("Price")]
        public double price { get; set; }
        [DisplayName("Image")]
        public byte[] image { get; set; }
        [DisplayName("How Old")]
        public int old { get; set; }
        [DisplayName("Book Condition")]
        public string book_condition { get; set; }
        [DisplayName("Discount")]
        public double discount { get; set; }
        public System.DateTime posted_date { get; set; }
        public int copies { get; set; }
    }
}
